---
  - name: Load config into supervisord
    supervisorctl: name={{project_name}}
                   state=present
                   # config=/etc/supervisor/conf.d/{{project_name}}.conf
    sudo: true

  - name: Restart supervisord
    supervisorctl: name={{project_name}}
                   state=started
                   # config=/etc/supervisor/conf.d/{{project_name}}.conf
    sudo: true

  - name: Restart nginx
    action: service name=nginx state=restarted
    sudo: true