---
- hosts: all
  sudo: true
  name: Perform common provision tasks.
  roles:
    - common

- hosts: databases
  gather_facts: false
  sudo: true
  name: Provision database
  roles:
    - database/provision

- hosts: webservers
  sudo: true
  name: Provision web application server
  roles:
    - webapp/provision

- hosts: webservers
  sudo: true
  name: Provision server
  roles:
    - server/provision

- include: deploy.yml