---
  - name: Install nginx configuration file.
    template: src=nginx.conf.j2
              dest=/etc/nginx/sites-available/{{ project_name }}.conf
    notify:
        - Restart nginx

  - name: Enable nginx configuration file.
    file: src=/etc/nginx/sites-available/{{ project_name }}.conf
          dest=/etc/nginx/sites-enabled/{{ project_name }}.conf
          state=link
    notify:
        - Restart nginx

  - name: Install supervisord configuration file
    template: src=supervisor.conf.j2
              dest=/etc/supervisor/conf.d/{{project_name}}.conf
    notify:
      - Load config into supervisord
      - Restart supervisord

  - name: Install gunicorn configuration file.
    template: src=gunicorn_conf.py.j2
              dest={{ project_root }}gunicorn_conf.py
              owner={{ project_user }}
    notify:
      - Load config into supervisord
      - Restart supervisord