---
  - name: Create the project database.
    postgresql_db: name={{ database_name }}
    sudo: true
    sudo_user: postgres

  - name: Create a user for the application
    postgresql_user: name={{ project_user }}
                     password={{ database_password }}
                     db={{ database_name }}
                     priv=ALL
    sudo: true
    sudo_user: postgres

  - name: Restrict the permissions of the database user.
    postgresql_user: name={{ project_user }}
                     password={{ database_password }}
                     role_attr_flags=NOSUPERUSER,NOCREATEDB
    sudo: true
    sudo_user: postgres