---
  - name: Create project user.
    user: name={{project_user}}
          group=www-data
          state=present
          shell='/bin/bash'

  - name: Ensure root can use SSH agent forwarding of default user
    lineinfile: dest=/etc/sudoers
                state=present
                regexp='^Defaults env_keep.*"SSH_AUTH_SOCK"$'
                line='Defaults env_keep += "SSH_AUTH_SOCK"'

  - name: Create the SSH directory.
    file: state=directory path=/home/{{project_user}}/.ssh/

  - name: Set up authorized_keys for the deploy user
    authorized_key: user={{project_user}}
                  key="{{ item }}"
    with_file:
      - ~/.ssh/id_rsa.pub

  - name: Add 'known_hosts' to ~/.ssh
    copy: src=known_hosts
          dest=/home/{{project_user}}/.ssh/known_hosts
          owner={{project_user}}

  - name: Create log folder
    file: path={{log_root}}
          owner={{project_user}}
          group=www-data
          mode=744
          state=directory
    sudo: true